# Generated by Django 3.2.4 on 2021-06-26 14:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_next_review_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 26, 14, 8, 44, 346971, tzinfo=utc)),
        ),
    ]
